name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Prepare database
        run: pnpm prisma migrate deploy --schema prisma/schema.prisma
      - name: Lint
        run: pnpm lint
      - name: Unit tests
        run: pnpm test:unit
      - name: Install Playwright browsers
        run: pnpm prepare:e2e
      - name: E2E tests
        run: pnpm test:e2e
        env:
          NUXT_TELEMETRY_DISABLED: '1'
          DATABASE_URL: 'file:./prisma/ci.db'
          GITHUB_TOKEN: 'mock'
          OPENAI_API_KEY: ''
      - name: Build
        run: pnpm build
